:toc: macro

image:https://travis-ci.org/fmarot/cifriendly-maven-plugin.svg?branch=master["Build Status", link="https://travis-ci.org/fmarot/cifriendly-maven-plugin"]
image:https://img.shields.io/maven-central/v/com.teamtter.maven/cifriendly-maven-plugin.svg["Latest Maven Central deployment", link="http://search.maven.org/#search%7Cga%7C1%7Ccom.teamtter.maven"]

:var_version: 1.0.3-SNAPSHOT

toc::[]


= Goal

https://github.com/mojohaus/flatten-maven-plugin/issues/51

http://blog.soebes.de/blog/2017/04/02/maven-pom-files-without-a-version-in-it/

== flatten

Replace the '${revision}' variables in all pom.xml of the MultiModule Maven Project with the real hardcoded version found in the upper pom's properties/revision node.

For example all child pom's "${revision}" version in their <parent> declaration will be replaced with the hardcoded "1.2.3-SNAPSHOT" if the upper pom contains: 

[source,xml]
----
<properties>
	<revision>1.2.3-SNAPSHOT</revision>
	...
</properties>
----
 

== unflatten

First, in the upper pom, the hardcoded version is transfered into the properties/revision node, overwriting any previous value.
So after a Maven release, the properties/revision node will see the correct version again.

Then it replaces the hardcoded version in all the poms (including the upper one) with a "${revision}" variable. In the upper pom.

= Warning: caveats of CI friendly

using CI friendly Maven forces the local dev to always execute from the upper pomso that ${revision} is defined. Otherwise child pom will not know their parent.

So we have to use the --projects feature of Maven from the root if we want to build only a specific child. We can not build directly from its sub-directory.

= Usage



[subs="attributes"]
----
mvn com.teamtter.maven:cifriendly-maven-plugin:{var_version}:unflatten
----

= Technical details

the library "decentxml" is used to keep pom formatting 